install: true
language: node_js
node_js:
  - 7
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_S3_BUCKET
  skip_cleanup: true
  acl: public_read
